services:
  mongo:
    image: mongo:6
    container_name: mongodb_todo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: todo-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend/todo
    container_name: todo-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mongo-data:
