# ---------- Build Angular ----------
FROM node:20-alpine as build

WORKDIR /app

# Copy only package.json + lock file first for better caching
COPY package*.json ./

RUN npm install

# Copy the rest of the source code
COPY . .

# Build Angular app in production mode
RUN npm run build --configuration=production

# ---------- Serve with Nginx ----------
FROM nginx:alpine

# Copy Angular build output into the standard Nginx html folder
COPY --from=build /app/dist/todo/browser /usr/share/nginx/html

# Copy custom Nginx config to support Angular routing
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
